package ru.alexandrorlov.testhammersystem.base

import ru.alexandrorlov.testhammersystem.ui.model.EntityMeal
import ru.alexandrorlov.testhammersystem.ui.model.Meals

fun Meals.toEntityMeal() : EntityMeal {
    val meal = this.meals?.first()
    return EntityMeal(
        id = meal?.id,
        title = meal?.title,
        drinkAlternate = meal?.drinkAlternate,
        category = meal?.category,
        area = meal?.area,
        description = meal?.description,
        urlThumb = meal?.urlThumb,
        tags = meal?.tags,
        urlYoutube = meal?.urlYoutube,
        ingredient1 = meal?.ingredient1,
        ingredient2 = meal?.ingredient2,
        ingredient3 = meal?.ingredient3,
        ingredient4 = meal?.ingredient4,
        ingredient5 = meal?.ingredient5,
        ingredient6 = meal?.ingredient6,
        ingredient7 = meal?.ingredient7,
        ingredient8 = meal?.ingredient8,
        ingredient9 = meal?.ingredient9,
        ingredient10 = meal?.ingredient10,
        ingredient11 = meal?.ingredient11,
        ingredient12 = meal?.ingredient12,
        ingredient13 = meal?.ingredient13,
        ingredient14 = meal?.ingredient14,
        ingredient15 = meal?.ingredient15,
        ingredient16 = meal?.ingredient16,
        ingredient17 = meal?.ingredient17,
        ingredient18 = meal?.ingredient18,
        ingredient19 = meal?.ingredient19,
        ingredient20 = meal?.ingredient20,
        measure1 = meal?.measure1,
        measure2 = meal?.measure2,
        measure3 = meal?.measure3,
        measure4 = meal?.measure4,
        measure5 = meal?.measure5,
        measure6 = meal?.measure6,
        measure7 = meal?.measure7,
        measure8 = meal?.measure8,
        measure9 = meal?.measure9,
        measure10 = meal?.measure10,
        measure11 = meal?.measure11,
        measure12 = meal?.measure12,
        measure13 = meal?.measure13,
        measure14 = meal?.measure14,
        measure15 = meal?.measure15,
        measure16 = meal?.measure16,
        measure17 = meal?.measure17,
        measure18 = meal?.measure18,
        measure19 = meal?.measure19,
        measure20 = meal?.measure20,
        source = meal?.source,
        imageSource = meal?.imageSource,
        creativeCommonsConfirmed = meal?.creativeCommonsConfirmed,
        dateModified = meal?.dateModified,
    )
}